# before_install:
# - sudo apt update && sudo apt install texlive-full
script:
- mkdir _build
# - uplatex -output-directory _build semi.tex
# - dvipdfmx -o _build/semi.pdf _build/semi.dvi
deploy:
  provider: releases
  file: semi.tex
  skip_cleanup: true
  api_key:
    secure: eRMsHdkqdyZp6YmKw386J0w0C0VmtLUmF+WgjZU26OBmdUE3iefoIU8e16wX8k7Ib1aBTovQlOFASIarhCjAxr0jehZ+4wK27NTdd829mMvIOHEg3l9eplwg+KeZXgn2WSG+od6eKRX8hcNJZts2nvG1K1IzZ0bmvWwHt7WZ2Y8o0F0VPpzvg34XGPumnQwiwgKtz+ckxhsTDxgF8exB26kI9OXRiTENJqJARPdlDPkeYdvN048mKFB6a4JrPL4PvtgmpeIgMUF1eC54YTsK1k5LTou5I9HUlOwy2tRyh2goujKlLBDNyBwKsrp2fYuKpQNMWiVQ8whW7jvIfsCLjGgmAN6LMcMVtb4LcBHn43qppwtrpoCbRaR8lIozhxJVWnXh9Lz+8IzmLs5uLRL6QFCwuLwoZamOC6OUY6oSDyKetidpL8dmX6rH+bMY+qqZsTQvGvYCIPLffKsMgT4jziHlnmjhUc0Z9LPOFwxoXEC6pT2gtkmPyZRqZsq9QqhjgzGNxPwqwDTi1TW5QQpIM8ZZ3SWZ0QwsjdpQ4gR5nL4z5s7uSV0MWxRuh33XHdWwBdg+Y5ahhQCkFd4R124f47JNlLplpUd/BW7gwhlphzAQIAI6Bi0iNMoYZ5Ki6lwy3EVNQH2oPoWwOKTrIH/qhRO8AUH8aI0byWYGK4P5ix4=
  on:
    repo: terakun/discrete-convex-analysis
    tags: false
