env:
  global:
  - secure: zPH0+dlSnNgaLOqlytmSIEF+Kw1YqLEO/1INu/heQSBzqZYHFjfGMlanIz5J4wC/7rMrAKbRJoBy2bgOQm1jxkK3CYTQXKAQopOIdn9mvCiq+NLBdTGXc+wgwiLuW/guOirdmqlKSy9hkOPi5KgHdy9dS1q0+wFWopHL1WN+kPkPYpbeP0rSi9hidFMracepQ7pQv9WUIMeyl7durshhCS84v3povTeYxsZ0Yp/LTTbPqV/RJ0U+9YHci0rzq+fuOuvavW+SYYF3tBiY1P+6+f2n7MkBvssxu46JeD1517l6ARTaYyW5vfRwLo/BJcQXZ8lVQ5f3yiIjjVnOTc5Kxqe9LbpH42ZyVv9JZbhfkDgQfx3/+HPKuo5yLWa9tfx+4bMDBLpAVUVuBfYQji+XVLB564URYrlmOWMXwq/80LwS/CDay9QQgpcWK6PghMhyXDbJUfVqKSzUHaIDGJB/Wcitoo5g3XRhxmVPuzD/8MBW8aC5+ySXXGMResPDA4HP4mOPx7NXnBKwhyCuH55ZMpnwj/J0uL/oYsWhLHaT3++z9EDFuT8rfQEjDeJ/T7wk8nPL43AFLQhvk31rpfAOTb0f6quGVzSKTU0cd7leUGyPZ4FAQaIQ+BWRpYrfe8sXXN9+rLEDLmZegT2vrroJclJoYjmNLMjaMocifdgFNR8=
before_install:
- sudo apt update && sudo apt install texlive-full
script:
- mkdir _build
- uplatex -output-directory _build semi.tex
- dvipdfmx -o _build/semi.pdf _build/semi.dvi
deploy:
  provider: releases
  file: _build/semi.pdf
  skip_cleanup: true
  api_key:
    secure: eRMsHdkqdyZp6YmKw386J0w0C0VmtLUmF+WgjZU26OBmdUE3iefoIU8e16wX8k7Ib1aBTovQlOFASIarhCjAxr0jehZ+4wK27NTdd829mMvIOHEg3l9eplwg+KeZXgn2WSG+od6eKRX8hcNJZts2nvG1K1IzZ0bmvWwHt7WZ2Y8o0F0VPpzvg34XGPumnQwiwgKtz+ckxhsTDxgF8exB26kI9OXRiTENJqJARPdlDPkeYdvN048mKFB6a4JrPL4PvtgmpeIgMUF1eC54YTsK1k5LTou5I9HUlOwy2tRyh2goujKlLBDNyBwKsrp2fYuKpQNMWiVQ8whW7jvIfsCLjGgmAN6LMcMVtb4LcBHn43qppwtrpoCbRaR8lIozhxJVWnXh9Lz+8IzmLs5uLRL6QFCwuLwoZamOC6OUY6oSDyKetidpL8dmX6rH+bMY+qqZsTQvGvYCIPLffKsMgT4jziHlnmjhUc0Z9LPOFwxoXEC6pT2gtkmPyZRqZsq9QqhjgzGNxPwqwDTi1TW5QQpIM8ZZ3SWZ0QwsjdpQ4gR5nL4z5s7uSV0MWxRuh33XHdWwBdg+Y5ahhQCkFd4R124f47JNlLplpUd/BW7gwhlphzAQIAI6Bi0iNMoYZ5Ki6lwy3EVNQH2oPoWwOKTrIH/qhRO8AUH8aI0byWYGK4P5ix4=
  on:
    repo: terakun/discrete-convex-analysis
    tags: false
