script:
- mkdir _build
deploy:
  provider: releases
  api_key:
    secure: 64GGi0/Cb34LD4yP12PW6Tw13cWch+2KVIFVbgEp1VN1V7MPFbSxAx2I5mJQ+0Nz216kZS1JagOszL8wn0fTBKeAEUQvrcqZW/jWV+YZx+fwEMgzO5UGG2UlHvaac6IW5Zq5w8lV5WwA7DuKWkYXB0XcqebVWN65xY/ugngSg2wKHCk/LX7WLh4z6WVP+UsJgI1+hsiVLn693syRG912slp6Bl3lfNvhFxPMBwLZ8/5dg3NlRpo+nnYQzoLQuak8O5tCodDnDRSYZSIzUORLl2ajBEzkK3yzTEWF/x2DRSeni7hJAdVgP7eQffVirMLQIpnU6fi+sXzRW6EB2mdBT4p53WEqBF0p+LpuBd9NxRUl9EDci298zHRPBIx2lzkVJ4a41bkIZdXB/qzeL6YCYyNeDtHLVyUz3jCzkkvtTQGcsfM30hl0X2BgaGnPCEYKE6vp08C6rtxoo2ZIf9Dw6KifG1cJqdiNEy0y4OIuvQyV8+jQxxrOltTUAcTx4SIfNuhTJosvEH176LjyYflH2CvGDJcsSbsP+cdFOf0t4f/NgD78eX9BxEi9MOYzznjWGvuBQOMXQIkyRUZbKfdewGgzUsEEAoazYgogYH5sW2i+e3yocSYjR5W3QU3DzvI1oKDmcSdeEhWloEVgEhAmXsjF7/Uke0SwgALDom/ZQGA=
  file:
  - "semi.tex"
  on:
    repo: terakun/discrete-convex-analysis
    tags: false
  skip_cleanup: true
